name: Chapter Frontend CI/CD

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_S3_BUCKET_NAME:
        required: true
    inputs:
      ENVIRONMENT:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Build
      run: |
        npm install
        npm run build
    
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          dist
          !dist/**/*.md
        retention-days: 1

  deploy:
    name: Deploy to AWS
    needs: build
    runs-on: ubuntu-22.04
    environment: ${{ inputs.ENVIRONMENT }}
    
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: artifacts

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          
      - name: Sync S3
        run: aws s3 sync ./ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
