name: SOPS

on:
  workflow_dispatch:

jobs:
  sops:
    name: test-sops-and-kms
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup SOPS
      run: |
        curl -LO https://github.com/getsops/sops/releases/download/v3.8.0-rc.1/sops-v3.8.0-rc.1.linux.amd64
        mv sops-v3.8.0-rc.1.linux.amd64 /usr/local/bin/sops
        chmod +x /usr/local/bin/sops

    - name: Test sops
      run: |
        sops -v

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Get encypted values
      run: |
        sops exec-env .env.enc.yaml 'echo $VITE_API_BASE_URL & echo $VITE_TWITTER_REDIRECT_URI'

    - name: Cleanup
      run: |
        rm -f .env.enc.yaml