name: SOPS

on:
  workflow_dispatch:

jobs:
  sops:
    name: TEST SOPS & PGP
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup SOPS
      run: |
        curl -LO https://github.com/getsops/sops/releases/download/v3.8.0-rc.1/sops-v3.8.0-rc.1.linux.amd64
        mv sops-v3.8.0-rc.1.linux.amd64 /usr/local/bin/sops
        chmod +x /usr/local/bin/sops

    - name: Test tools
      run: |
        sops -v
        gpg --list-keys

    - name: Import key
      run: |
        echo ${{ secrets.PGP_PRIVATE_KEY }} > pgp.key
        gpg --import pgp.key

    - name: Get encypted values
      run: |
        sops -d .env.enc.yaml

    - name: Cleanup
      run: |
        rm -f .env.enc.yaml